name: Deploy to WordPress.org
on:
  release:
    types: [published]
jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v3
      with:
        submodules: true
        token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}

    - name: Initialize and update submodules
      run: |
        # Ensure all submodules (dashboard, etc.) are fully updated
        git submodule update --init --recursive

    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: shopkeeper-extender